# Generated by Django 5.2.7 on 2026-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
